---
apiVersion: v1
kind: Template
metadata:
  name: jupyterhub-template
parameters:
  - name: "namespace"
    displayName: "namespace "
    description: "details"
    value: "abhutad-test"
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: abhutad-2
    name: abhutad-2
    namespace: ${namespace}
  spec:
    replicas: 1
    selector:
      app: abhutad-2
      deploymentconfig: abhutad-2
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
      spec:
        containers:
          - image: >-
              nexusdev.discoverfinancial.com:18082/abhutad-jupyterhub/abhutad@sha256:cec5a30cf775e97f70187cc3cd8546dfbc6a8f4080087d2459cae9b7e4dad101
            imagePullPolicy: IfNotPresent
            name: abhutad-2
            ports:
              - containerPort: 8000
                protocol: TCP
              - containerPort: 8888
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /mnt
                name: volume-twrt6
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: volume-twrt6
            persistentVolumeClaim:
              claimName: abhutad-test-storage
    test: false
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - abhutad-2
          from:
            kind: ImageStreamTag
            name: 'abhutad-2:2'
            namespace: abhutad-test
          lastTriggeredImage: >-
            nexusdev.discoverfinancial.com:18082/abhutad-jupyterhub/abhutad@sha256:cec5a30cf775e97f70187cc3cd8546dfbc6a8f4080087d2459cae9b7e4dad101
        type: ImageChange
